//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ForumModel", "FK__Answer__Question__07F6335A", "AskQuestion", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Forums.AskQuestion), "Answer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Forums.Answer), true)]
[assembly: EdmRelationshipAttribute("ForumModel", "FK__Answer__UserId__08EA5793", "tbl_user", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Forums.tbl_user), "Answer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Forums.Answer), true)]
[assembly: EdmRelationshipAttribute("ForumModel", "FK__AskQuesti__UserI__03317E3D", "tbl_user", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Forums.tbl_user), "AskQuestion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Forums.AskQuestion), true)]
[assembly: EdmRelationshipAttribute("ForumModel", "FK__userDetai__UserI__2E1BDC42", "tbl_user", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Forums.tbl_user), "userDetails", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Forums.userDetail), true)]

#endregion

namespace Forums
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ForumEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ForumEntities object using the connection string found in the 'ForumEntities' section of the application configuration file.
        /// </summary>
        public ForumEntities() : base("name=ForumEntities", "ForumEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ForumEntities object.
        /// </summary>
        public ForumEntities(string connectionString) : base(connectionString, "ForumEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ForumEntities object.
        /// </summary>
        public ForumEntities(EntityConnection connection) : base(connection, "ForumEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Answer> Answers
        {
            get
            {
                if ((_Answers == null))
                {
                    _Answers = base.CreateObjectSet<Answer>("Answers");
                }
                return _Answers;
            }
        }
        private ObjectSet<Answer> _Answers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AskQuestion> AskQuestions
        {
            get
            {
                if ((_AskQuestions == null))
                {
                    _AskQuestions = base.CreateObjectSet<AskQuestion>("AskQuestions");
                }
                return _AskQuestions;
            }
        }
        private ObjectSet<AskQuestion> _AskQuestions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_user> tbl_user
        {
            get
            {
                if ((_tbl_user == null))
                {
                    _tbl_user = base.CreateObjectSet<tbl_user>("tbl_user");
                }
                return _tbl_user;
            }
        }
        private ObjectSet<tbl_user> _tbl_user;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<userDetail> userDetails
        {
            get
            {
                if ((_userDetails == null))
                {
                    _userDetails = base.CreateObjectSet<userDetail>("userDetails");
                }
                return _userDetails;
            }
        }
        private ObjectSet<userDetail> _userDetails;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Answers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAnswers(Answer answer)
        {
            base.AddObject("Answers", answer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AskQuestions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAskQuestions(AskQuestion askQuestion)
        {
            base.AddObject("AskQuestions", askQuestion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_user EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_user(tbl_user tbl_user)
        {
            base.AddObject("tbl_user", tbl_user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the userDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTouserDetails(userDetail userDetail)
        {
            base.AddObject("userDetails", userDetail);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<ShowTags_Result1> ShowTags()
        {
            return base.ExecuteFunction<ShowTags_Result1>("ShowTags");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<ShowUser_Result> ShowUser()
        {
            return base.ExecuteFunction<ShowUser_Result>("ShowUser");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="id">No Metadata Documentation available.</param>
        public ObjectResult<ShowUserDetails_Result1> ShowUserDetails(Nullable<global::System.Int32> id)
        {
            ObjectParameter idParameter;
            if (id.HasValue)
            {
                idParameter = new ObjectParameter("id", id);
            }
            else
            {
                idParameter = new ObjectParameter("id", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<ShowUserDetails_Result1>("ShowUserDetails", idParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ForumModel", Name="Answer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Answer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Answer object.
        /// </summary>
        /// <param name="answerId">Initial value of the AnswerId property.</param>
        public static Answer CreateAnswer(global::System.Int32 answerId)
        {
            Answer answer = new Answer();
            answer.AnswerId = answerId;
            return answer;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AnswerId
        {
            get
            {
                return _AnswerId;
            }
            set
            {
                if (_AnswerId != value)
                {
                    OnAnswerIdChanging(value);
                    ReportPropertyChanging("AnswerId");
                    _AnswerId = StructuralObject.SetValidValue(value, "AnswerId");
                    ReportPropertyChanged("AnswerId");
                    OnAnswerIdChanged();
                }
            }
        }
        private global::System.Int32 _AnswerId;
        partial void OnAnswerIdChanging(global::System.Int32 value);
        partial void OnAnswerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AnswerDetails
        {
            get
            {
                return _AnswerDetails;
            }
            set
            {
                OnAnswerDetailsChanging(value);
                ReportPropertyChanging("AnswerDetails");
                _AnswerDetails = StructuralObject.SetValidValue(value, true, "AnswerDetails");
                ReportPropertyChanged("AnswerDetails");
                OnAnswerDetailsChanged();
            }
        }
        private global::System.String _AnswerDetails;
        partial void OnAnswerDetailsChanging(global::System.String value);
        partial void OnAnswerDetailsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DateAndTime
        {
            get
            {
                return _DateAndTime;
            }
            set
            {
                OnDateAndTimeChanging(value);
                ReportPropertyChanging("DateAndTime");
                _DateAndTime = StructuralObject.SetValidValue(value, true, "DateAndTime");
                ReportPropertyChanged("DateAndTime");
                OnDateAndTimeChanged();
            }
        }
        private global::System.String _DateAndTime;
        partial void OnDateAndTimeChanging(global::System.String value);
        partial void OnDateAndTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> QuestionId
        {
            get
            {
                return _QuestionId;
            }
            set
            {
                OnQuestionIdChanging(value);
                ReportPropertyChanging("QuestionId");
                _QuestionId = StructuralObject.SetValidValue(value, "QuestionId");
                ReportPropertyChanged("QuestionId");
                OnQuestionIdChanged();
            }
        }
        private Nullable<global::System.Int32> _QuestionId;
        partial void OnQuestionIdChanging(Nullable<global::System.Int32> value);
        partial void OnQuestionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, "UserId");
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private Nullable<global::System.Int32> _UserId;
        partial void OnUserIdChanging(Nullable<global::System.Int32> value);
        partial void OnUserIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ForumModel", "FK__Answer__Question__07F6335A", "AskQuestion")]
        public AskQuestion AskQuestion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AskQuestion>("ForumModel.FK__Answer__Question__07F6335A", "AskQuestion").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AskQuestion>("ForumModel.FK__Answer__Question__07F6335A", "AskQuestion").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<AskQuestion> AskQuestionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AskQuestion>("ForumModel.FK__Answer__Question__07F6335A", "AskQuestion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<AskQuestion>("ForumModel.FK__Answer__Question__07F6335A", "AskQuestion", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ForumModel", "FK__Answer__UserId__08EA5793", "tbl_user")]
        public tbl_user tbl_user
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_user>("ForumModel.FK__Answer__UserId__08EA5793", "tbl_user").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_user>("ForumModel.FK__Answer__UserId__08EA5793", "tbl_user").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_user> tbl_userReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_user>("ForumModel.FK__Answer__UserId__08EA5793", "tbl_user");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_user>("ForumModel.FK__Answer__UserId__08EA5793", "tbl_user", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ForumModel", Name="AskQuestion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AskQuestion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AskQuestion object.
        /// </summary>
        /// <param name="questionId">Initial value of the QuestionId property.</param>
        public static AskQuestion CreateAskQuestion(global::System.Int32 questionId)
        {
            AskQuestion askQuestion = new AskQuestion();
            askQuestion.QuestionId = questionId;
            return askQuestion;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QuestionId
        {
            get
            {
                return _QuestionId;
            }
            set
            {
                if (_QuestionId != value)
                {
                    OnQuestionIdChanging(value);
                    ReportPropertyChanging("QuestionId");
                    _QuestionId = StructuralObject.SetValidValue(value, "QuestionId");
                    ReportPropertyChanged("QuestionId");
                    OnQuestionIdChanged();
                }
            }
        }
        private global::System.Int32 _QuestionId;
        partial void OnQuestionIdChanging(global::System.Int32 value);
        partial void OnQuestionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String QuestionTitle
        {
            get
            {
                return _QuestionTitle;
            }
            set
            {
                OnQuestionTitleChanging(value);
                ReportPropertyChanging("QuestionTitle");
                _QuestionTitle = StructuralObject.SetValidValue(value, true, "QuestionTitle");
                ReportPropertyChanged("QuestionTitle");
                OnQuestionTitleChanged();
            }
        }
        private global::System.String _QuestionTitle;
        partial void OnQuestionTitleChanging(global::System.String value);
        partial void OnQuestionTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String QuestionDetails
        {
            get
            {
                return _QuestionDetails;
            }
            set
            {
                OnQuestionDetailsChanging(value);
                ReportPropertyChanging("QuestionDetails");
                _QuestionDetails = StructuralObject.SetValidValue(value, true, "QuestionDetails");
                ReportPropertyChanged("QuestionDetails");
                OnQuestionDetailsChanged();
            }
        }
        private global::System.String _QuestionDetails;
        partial void OnQuestionDetailsChanging(global::System.String value);
        partial void OnQuestionDetailsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tags
        {
            get
            {
                return _Tags;
            }
            set
            {
                OnTagsChanging(value);
                ReportPropertyChanging("Tags");
                _Tags = StructuralObject.SetValidValue(value, true, "Tags");
                ReportPropertyChanged("Tags");
                OnTagsChanged();
            }
        }
        private global::System.String _Tags;
        partial void OnTagsChanging(global::System.String value);
        partial void OnTagsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DateAndTime
        {
            get
            {
                return _DateAndTime;
            }
            set
            {
                OnDateAndTimeChanging(value);
                ReportPropertyChanging("DateAndTime");
                _DateAndTime = StructuralObject.SetValidValue(value, true, "DateAndTime");
                ReportPropertyChanged("DateAndTime");
                OnDateAndTimeChanged();
            }
        }
        private global::System.String _DateAndTime;
        partial void OnDateAndTimeChanging(global::System.String value);
        partial void OnDateAndTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, "UserId");
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private Nullable<global::System.Int32> _UserId;
        partial void OnUserIdChanging(Nullable<global::System.Int32> value);
        partial void OnUserIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ForumModel", "FK__Answer__Question__07F6335A", "Answer")]
        public EntityCollection<Answer> Answers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Answer>("ForumModel.FK__Answer__Question__07F6335A", "Answer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Answer>("ForumModel.FK__Answer__Question__07F6335A", "Answer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ForumModel", "FK__AskQuesti__UserI__03317E3D", "tbl_user")]
        public tbl_user tbl_user
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_user>("ForumModel.FK__AskQuesti__UserI__03317E3D", "tbl_user").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_user>("ForumModel.FK__AskQuesti__UserI__03317E3D", "tbl_user").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_user> tbl_userReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_user>("ForumModel.FK__AskQuesti__UserI__03317E3D", "tbl_user");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_user>("ForumModel.FK__AskQuesti__UserI__03317E3D", "tbl_user", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ForumModel", Name="tbl_user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_user : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_user object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        public static tbl_user Createtbl_user(global::System.Int32 userId, global::System.String name, global::System.String email, global::System.String password)
        {
            tbl_user tbl_user = new tbl_user();
            tbl_user.UserId = userId;
            tbl_user.Name = name;
            tbl_user.Email = email;
            tbl_user.Password = password;
            return tbl_user;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value, "UserId");
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false, "Password");
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ForumModel", "FK__Answer__UserId__08EA5793", "Answer")]
        public EntityCollection<Answer> Answers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Answer>("ForumModel.FK__Answer__UserId__08EA5793", "Answer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Answer>("ForumModel.FK__Answer__UserId__08EA5793", "Answer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ForumModel", "FK__AskQuesti__UserI__03317E3D", "AskQuestion")]
        public EntityCollection<AskQuestion> AskQuestions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AskQuestion>("ForumModel.FK__AskQuesti__UserI__03317E3D", "AskQuestion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AskQuestion>("ForumModel.FK__AskQuesti__UserI__03317E3D", "AskQuestion", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ForumModel", "FK__userDetai__UserI__2E1BDC42", "userDetails")]
        public EntityCollection<userDetail> userDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<userDetail>("ForumModel.FK__userDetai__UserI__2E1BDC42", "userDetails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<userDetail>("ForumModel.FK__userDetai__UserI__2E1BDC42", "userDetails", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ForumModel", Name="userDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class userDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new userDetail object.
        /// </summary>
        /// <param name="userDetailsId">Initial value of the UserDetailsId property.</param>
        public static userDetail CreateuserDetail(global::System.Int32 userDetailsId)
        {
            userDetail userDetail = new userDetail();
            userDetail.UserDetailsId = userDetailsId;
            return userDetail;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserDetailsId
        {
            get
            {
                return _UserDetailsId;
            }
            set
            {
                if (_UserDetailsId != value)
                {
                    OnUserDetailsIdChanging(value);
                    ReportPropertyChanging("UserDetailsId");
                    _UserDetailsId = StructuralObject.SetValidValue(value, "UserDetailsId");
                    ReportPropertyChanged("UserDetailsId");
                    OnUserDetailsIdChanged();
                }
            }
        }
        private global::System.Int32 _UserDetailsId;
        partial void OnUserDetailsIdChanging(global::System.Int32 value);
        partial void OnUserDetailsIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true, "Phone");
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String location
        {
            get
            {
                return _location;
            }
            set
            {
                OnlocationChanging(value);
                ReportPropertyChanging("location");
                _location = StructuralObject.SetValidValue(value, true, "location");
                ReportPropertyChanged("location");
                OnlocationChanged();
            }
        }
        private global::System.String _location;
        partial void OnlocationChanging(global::System.String value);
        partial void OnlocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String carear
        {
            get
            {
                return _carear;
            }
            set
            {
                OncarearChanging(value);
                ReportPropertyChanging("carear");
                _carear = StructuralObject.SetValidValue(value, true, "carear");
                ReportPropertyChanged("carear");
                OncarearChanged();
            }
        }
        private global::System.String _carear;
        partial void OncarearChanging(global::System.String value);
        partial void OncarearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String about
        {
            get
            {
                return _about;
            }
            set
            {
                OnaboutChanging(value);
                ReportPropertyChanging("about");
                _about = StructuralObject.SetValidValue(value, true, "about");
                ReportPropertyChanged("about");
                OnaboutChanged();
            }
        }
        private global::System.String _about;
        partial void OnaboutChanging(global::System.String value);
        partial void OnaboutChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, "UserId");
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private Nullable<global::System.Int32> _UserId;
        partial void OnUserIdChanging(Nullable<global::System.Int32> value);
        partial void OnUserIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ForumModel", "FK__userDetai__UserI__2E1BDC42", "tbl_user")]
        public tbl_user tbl_user
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_user>("ForumModel.FK__userDetai__UserI__2E1BDC42", "tbl_user").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_user>("ForumModel.FK__userDetai__UserI__2E1BDC42", "tbl_user").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_user> tbl_userReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_user>("ForumModel.FK__userDetai__UserI__2E1BDC42", "tbl_user");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_user>("ForumModel.FK__userDetai__UserI__2E1BDC42", "tbl_user", value);
                }
            }
        }

        #endregion

    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="ForumModel", Name="ShowTags_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class ShowTags_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ShowTags_Result object.
        /// </summary>
        /// <param name="questionId">Initial value of the QuestionId property.</param>
        public static ShowTags_Result CreateShowTags_Result(global::System.Int32 questionId)
        {
            ShowTags_Result showTags_Result = new ShowTags_Result();
            showTags_Result.QuestionId = questionId;
            return showTags_Result;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QuestionId
        {
            get
            {
                return _QuestionId;
            }
            set
            {
                OnQuestionIdChanging(value);
                ReportPropertyChanging("QuestionId");
                _QuestionId = StructuralObject.SetValidValue(value, "QuestionId");
                ReportPropertyChanged("QuestionId");
                OnQuestionIdChanged();
            }
        }
        private global::System.Int32 _QuestionId;
        partial void OnQuestionIdChanging(global::System.Int32 value);
        partial void OnQuestionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String QuestionTitle
        {
            get
            {
                return _QuestionTitle;
            }
            set
            {
                OnQuestionTitleChanging(value);
                ReportPropertyChanging("QuestionTitle");
                _QuestionTitle = StructuralObject.SetValidValue(value, true, "QuestionTitle");
                ReportPropertyChanged("QuestionTitle");
                OnQuestionTitleChanged();
            }
        }
        private global::System.String _QuestionTitle;
        partial void OnQuestionTitleChanging(global::System.String value);
        partial void OnQuestionTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String QuestionDetails
        {
            get
            {
                return _QuestionDetails;
            }
            set
            {
                OnQuestionDetailsChanging(value);
                ReportPropertyChanging("QuestionDetails");
                _QuestionDetails = StructuralObject.SetValidValue(value, true, "QuestionDetails");
                ReportPropertyChanged("QuestionDetails");
                OnQuestionDetailsChanged();
            }
        }
        private global::System.String _QuestionDetails;
        partial void OnQuestionDetailsChanging(global::System.String value);
        partial void OnQuestionDetailsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tags
        {
            get
            {
                return _Tags;
            }
            set
            {
                OnTagsChanging(value);
                ReportPropertyChanging("Tags");
                _Tags = StructuralObject.SetValidValue(value, true, "Tags");
                ReportPropertyChanged("Tags");
                OnTagsChanged();
            }
        }
        private global::System.String _Tags;
        partial void OnTagsChanging(global::System.String value);
        partial void OnTagsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DateAndTime
        {
            get
            {
                return _DateAndTime;
            }
            set
            {
                OnDateAndTimeChanging(value);
                ReportPropertyChanging("DateAndTime");
                _DateAndTime = StructuralObject.SetValidValue(value, true, "DateAndTime");
                ReportPropertyChanged("DateAndTime");
                OnDateAndTimeChanged();
            }
        }
        private global::System.String _DateAndTime;
        partial void OnDateAndTimeChanging(global::System.String value);
        partial void OnDateAndTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, "UserId");
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private Nullable<global::System.Int32> _UserId;
        partial void OnUserIdChanging(Nullable<global::System.Int32> value);
        partial void OnUserIdChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="ForumModel", Name="ShowTags_Result1")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class ShowTags_Result1 : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ShowTags_Result1 object.
        /// </summary>
        /// <param name="questionId">Initial value of the QuestionId property.</param>
        public static ShowTags_Result1 CreateShowTags_Result1(global::System.Int32 questionId)
        {
            ShowTags_Result1 showTags_Result1 = new ShowTags_Result1();
            showTags_Result1.QuestionId = questionId;
            return showTags_Result1;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QuestionId
        {
            get
            {
                return _QuestionId;
            }
            set
            {
                OnQuestionIdChanging(value);
                ReportPropertyChanging("QuestionId");
                _QuestionId = StructuralObject.SetValidValue(value, "QuestionId");
                ReportPropertyChanged("QuestionId");
                OnQuestionIdChanged();
            }
        }
        private global::System.Int32 _QuestionId;
        partial void OnQuestionIdChanging(global::System.Int32 value);
        partial void OnQuestionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String QuestionTitle
        {
            get
            {
                return _QuestionTitle;
            }
            set
            {
                OnQuestionTitleChanging(value);
                ReportPropertyChanging("QuestionTitle");
                _QuestionTitle = StructuralObject.SetValidValue(value, true, "QuestionTitle");
                ReportPropertyChanged("QuestionTitle");
                OnQuestionTitleChanged();
            }
        }
        private global::System.String _QuestionTitle;
        partial void OnQuestionTitleChanging(global::System.String value);
        partial void OnQuestionTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String QuestionDetails
        {
            get
            {
                return _QuestionDetails;
            }
            set
            {
                OnQuestionDetailsChanging(value);
                ReportPropertyChanging("QuestionDetails");
                _QuestionDetails = StructuralObject.SetValidValue(value, true, "QuestionDetails");
                ReportPropertyChanged("QuestionDetails");
                OnQuestionDetailsChanged();
            }
        }
        private global::System.String _QuestionDetails;
        partial void OnQuestionDetailsChanging(global::System.String value);
        partial void OnQuestionDetailsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tags
        {
            get
            {
                return _Tags;
            }
            set
            {
                OnTagsChanging(value);
                ReportPropertyChanging("Tags");
                _Tags = StructuralObject.SetValidValue(value, true, "Tags");
                ReportPropertyChanged("Tags");
                OnTagsChanged();
            }
        }
        private global::System.String _Tags;
        partial void OnTagsChanging(global::System.String value);
        partial void OnTagsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DateAndTime
        {
            get
            {
                return _DateAndTime;
            }
            set
            {
                OnDateAndTimeChanging(value);
                ReportPropertyChanging("DateAndTime");
                _DateAndTime = StructuralObject.SetValidValue(value, true, "DateAndTime");
                ReportPropertyChanged("DateAndTime");
                OnDateAndTimeChanged();
            }
        }
        private global::System.String _DateAndTime;
        partial void OnDateAndTimeChanging(global::System.String value);
        partial void OnDateAndTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, "UserId");
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private Nullable<global::System.Int32> _UserId;
        partial void OnUserIdChanging(Nullable<global::System.Int32> value);
        partial void OnUserIdChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="ForumModel", Name="ShowUser_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class ShowUser_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ShowUser_Result object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        public static ShowUser_Result CreateShowUser_Result(global::System.Int32 userId, global::System.String name, global::System.String email, global::System.String password)
        {
            ShowUser_Result showUser_Result = new ShowUser_Result();
            showUser_Result.UserId = userId;
            showUser_Result.Name = name;
            showUser_Result.Email = email;
            showUser_Result.Password = password;
            return showUser_Result;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, "UserId");
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false, "Password");
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="ForumModel", Name="ShowUserDetails_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class ShowUserDetails_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ShowUserDetails_Result object.
        /// </summary>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        public static ShowUserDetails_Result CreateShowUserDetails_Result(global::System.String name, global::System.String email)
        {
            ShowUserDetails_Result showUserDetails_Result = new ShowUserDetails_Result();
            showUserDetails_Result.Name = name;
            showUserDetails_Result.Email = email;
            return showUserDetails_Result;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true, "Phone");
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String location
        {
            get
            {
                return _location;
            }
            set
            {
                OnlocationChanging(value);
                ReportPropertyChanging("location");
                _location = StructuralObject.SetValidValue(value, true, "location");
                ReportPropertyChanged("location");
                OnlocationChanged();
            }
        }
        private global::System.String _location;
        partial void OnlocationChanging(global::System.String value);
        partial void OnlocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String carear
        {
            get
            {
                return _carear;
            }
            set
            {
                OncarearChanging(value);
                ReportPropertyChanging("carear");
                _carear = StructuralObject.SetValidValue(value, true, "carear");
                ReportPropertyChanged("carear");
                OncarearChanged();
            }
        }
        private global::System.String _carear;
        partial void OncarearChanging(global::System.String value);
        partial void OncarearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String about
        {
            get
            {
                return _about;
            }
            set
            {
                OnaboutChanging(value);
                ReportPropertyChanging("about");
                _about = StructuralObject.SetValidValue(value, true, "about");
                ReportPropertyChanged("about");
                OnaboutChanged();
            }
        }
        private global::System.String _about;
        partial void OnaboutChanging(global::System.String value);
        partial void OnaboutChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="ForumModel", Name="ShowUserDetails_Result1")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class ShowUserDetails_Result1 : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ShowUserDetails_Result1 object.
        /// </summary>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        public static ShowUserDetails_Result1 CreateShowUserDetails_Result1(global::System.String name, global::System.String email)
        {
            ShowUserDetails_Result1 showUserDetails_Result1 = new ShowUserDetails_Result1();
            showUserDetails_Result1.Name = name;
            showUserDetails_Result1.Email = email;
            return showUserDetails_Result1;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true, "Phone");
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String location
        {
            get
            {
                return _location;
            }
            set
            {
                OnlocationChanging(value);
                ReportPropertyChanging("location");
                _location = StructuralObject.SetValidValue(value, true, "location");
                ReportPropertyChanged("location");
                OnlocationChanged();
            }
        }
        private global::System.String _location;
        partial void OnlocationChanging(global::System.String value);
        partial void OnlocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String carear
        {
            get
            {
                return _carear;
            }
            set
            {
                OncarearChanging(value);
                ReportPropertyChanging("carear");
                _carear = StructuralObject.SetValidValue(value, true, "carear");
                ReportPropertyChanged("carear");
                OncarearChanged();
            }
        }
        private global::System.String _carear;
        partial void OncarearChanging(global::System.String value);
        partial void OncarearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String about
        {
            get
            {
                return _about;
            }
            set
            {
                OnaboutChanging(value);
                ReportPropertyChanging("about");
                _about = StructuralObject.SetValidValue(value, true, "about");
                ReportPropertyChanged("about");
                OnaboutChanged();
            }
        }
        private global::System.String _about;
        partial void OnaboutChanging(global::System.String value);
        partial void OnaboutChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="ForumModel", Name="ShowUserDetails1_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class ShowUserDetails1_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ShowUserDetails1_Result object.
        /// </summary>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        public static ShowUserDetails1_Result CreateShowUserDetails1_Result(global::System.String name, global::System.String email)
        {
            ShowUserDetails1_Result showUserDetails1_Result = new ShowUserDetails1_Result();
            showUserDetails1_Result.Name = name;
            showUserDetails1_Result.Email = email;
            return showUserDetails1_Result;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true, "Phone");
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String location
        {
            get
            {
                return _location;
            }
            set
            {
                OnlocationChanging(value);
                ReportPropertyChanging("location");
                _location = StructuralObject.SetValidValue(value, true, "location");
                ReportPropertyChanged("location");
                OnlocationChanged();
            }
        }
        private global::System.String _location;
        partial void OnlocationChanging(global::System.String value);
        partial void OnlocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String carear
        {
            get
            {
                return _carear;
            }
            set
            {
                OncarearChanging(value);
                ReportPropertyChanging("carear");
                _carear = StructuralObject.SetValidValue(value, true, "carear");
                ReportPropertyChanged("carear");
                OncarearChanged();
            }
        }
        private global::System.String _carear;
        partial void OncarearChanging(global::System.String value);
        partial void OncarearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String about
        {
            get
            {
                return _about;
            }
            set
            {
                OnaboutChanging(value);
                ReportPropertyChanging("about");
                _about = StructuralObject.SetValidValue(value, true, "about");
                ReportPropertyChanged("about");
                OnaboutChanged();
            }
        }
        private global::System.String _about;
        partial void OnaboutChanging(global::System.String value);
        partial void OnaboutChanged();

        #endregion

    }

    #endregion

}
